[debug]

# editor, raceSetup, race
entry_point = "editor"

enable_audio = true

fixed_course_path = "asset/course/sandbox_course.toml"

ai_count = 29

fix_ai_color = false

draw_physics_lines = false

draw_scenery = true

print_diagnostics = true

boost_unlocked = false

skip_321go = false

disable_finish = false

# [-1.0, 1.0] (Out-of-range values are ignored.)
rubber_banding_rate = -2
